spring.application.name=product-management
server.port=${PORT:8080}

# H2 Database Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/productmanagement
#spring.datasource.username=root
#spring.datasource.password=password
spring.datasource.url=jdbc:mysql://avnadmin:AVNS_9eHbxVdJv93nvcNOmpc@mysql-21930436-pi2t-ba86.c.aivencloud.com:16278/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_9eHbxVdJv93nvcNOmpc

# JPA & Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=3600000

# Cache Configuration
spring.cache.type=simple